//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeBar.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        public Ingredients()
        {
            this.ProductIngredients = new HashSet<ProductIngredients>();
            this.Supplies = new HashSet<Supplies>();
        }
    
        public int IngredientID { get; set; }
        public string IngredientName { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> StockQuantity { get; set; }
        public Nullable<decimal> MinStockLevel { get; set; }
    
        public virtual ICollection<ProductIngredients> ProductIngredients { get; set; }
        public virtual ICollection<Supplies> Supplies { get; set; }
    }
}
