//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeBar.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDiscounts
    {
        public int ProductDiscountID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> DiscountID { get; set; }
    
        public virtual Discounts Discounts { get; set; }
        public virtual Products Products { get; set; }
    }
}
