//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeBar.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrderItems = new HashSet<OrderItems>();
            this.ProductDiscounts = new HashSet<ProductDiscounts>();
            this.ProductIngredients = new HashSet<ProductIngredients>();
            this.Reviews = new HashSet<Reviews>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<int> PreparationTime { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual ICollection<ProductDiscounts> ProductDiscounts { get; set; }
        public virtual ICollection<ProductIngredients> ProductIngredients { get; set; }
        public virtual ICollection<Reviews> Reviews { get; set; }
    }
}
