//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeBar.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public Suppliers()
        {
            this.Supplies = new HashSet<Supplies>();
        }
    
        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string ContactPhone { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Supplies> Supplies { get; set; }
    }
}
