//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeBar.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplies
    {
        public int SupplyID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> IngredientID { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<System.DateTime> SupplyDate { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
